# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitrans < Formula
  desc "Yet another task management tool."
  homepage "https://github.com/Qithub-BOT/QiiTrans/"
  version "1.0.0-RC3"

  on_macos do
    url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC3/QiiTrans_1.0.0-RC3_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "55fc5a995ac42d97e600f4e262e8ab0a13e6075daa2223f26d857be7b971fdad"

    def install
      bin.install "qiitrans"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC3/QiiTrans_1.0.0-RC3_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "40b47649ebf308e41217013f1b9131a040ec6c42db4e22c264b33e817dd4c022"

      def install
        bin.install "qiitrans"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC3/QiiTrans_1.0.0-RC3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5cfa6d542845e461c5351b4fc6e18212d336bf528ef5c85d78fe8d472be2c5ed"

      def install
        bin.install "qiitrans"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC3/QiiTrans_1.0.0-RC3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a60806a632a9e661e411800dfcfb1aa8a15b9273463efe713614bc9f51b66bbd"

      def install
        bin.install "qiitrans"
      end
    end
  end

  test do
    system "#{bin}/qiitrans --version"
  end
end
