# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitan < Formula
  desc "This is a sample app of github.com/Qithub-BOT/Qiitan-go. It simply prints 'Hello, Gopher!'."
  homepage "https://github.com/Qithub-BOT/Qiitan-go/"
  version "0.0.0-beta2"

  on_macos do
    url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta2/Qiitan-go_0.0.0-beta2_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "598550cd256df255dfe50a5c46340eb740dc7cdb29e24ce553bb1ea1d31d7d23"

    def install
      bin.install "qiitan"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta2/Qiitan-go_0.0.0-beta2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "19865d1f9f1b96efdccefdf6c966b5a846da1aadbd1f0c5b833e51019bdf9a0e"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta2/Qiitan-go_0.0.0-beta2_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "eec7f52e7fbf6f4755781893cb5515b88f782120b8043635c9180a8c8f441519"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta2/Qiitan-go_0.0.0-beta2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "050b0abf66190ca0300b302099222096b3104c86f0f3a9262f0ba47ba4813bd1"

      def install
        bin.install "qiitan"
      end
    end
  end

  test do
    system "#{bin}/qiitan --version"
  end
end
