# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitrans < Formula
  desc "Yet another task management tool."
  homepage "https://github.com/Qithub-BOT/QiiTrans/"
  version "1.0.0-RC4"

  on_macos do
    url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC4/QiiTrans_1.0.0-RC4_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "186501fa6842f83b503ea643c0dafcc909c1120a1351bf53c78cd0c2d2ed07d7"

    def install
      bin.install "qiitrans"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC4/QiiTrans_1.0.0-RC4_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "464cb8cb8db8435dc569971b3bfa2c054f1e052a8cafae6c8f0fe5ede499b221"

      def install
        bin.install "qiitrans"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC4/QiiTrans_1.0.0-RC4_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "05c191751e8e73e8df95ef94d349ad3062df6eabebdd33030dd87ea97091b93d"

      def install
        bin.install "qiitrans"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTrans/releases/download/v1.0.0-RC4/QiiTrans_1.0.0-RC4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0bd95de9316df508095c0bebf4f4b49fcd122cee3d44c423058c3e880a306518"

      def install
        bin.install "qiitrans"
      end
    end
  end

  test do
    system "#{bin}/qiitrans --version"
  end
end
