# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitan < Formula
  desc "This is a sample app of github.com/Qithub-BOT/Qiitan-go. It simply prints 'Hello, Gopher!'."
  homepage "https://github.com/Qithub-BOT/Qiitan-go/"
  version "0.0.0-alpha"

  on_macos do
    url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-alpha/Qiitan-go_0.0.0-alpha_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "6c96fdbdfabd12f4ab1dde847a165001d125d6e14271c253b0661b0b354d0377"

    def install
      bin.install "qiitan"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-alpha/Qiitan-go_0.0.0-alpha_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f3ba1afa91357fbb238030668ce66140004e25b745b19a7d9344a7bc96dbaaee"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-alpha/Qiitan-go_0.0.0-alpha_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "83f36c6ff4974202b1ebc874f0b03b6ff6edccf6cf5ba63953a2c62ba3a33694"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-alpha/Qiitan-go_0.0.0-alpha_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "e66cc2e01e69ed54a15f8b866e5c3426c90ed67231d1d7a02c7943c5c8f37bdc"

      def install
        bin.install "qiitan"
      end
    end
  end

  test do
    system "#{bin}/qiitan --version"
  end
end
