# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitask < Formula
  desc "Yet another task management tool."
  homepage "https://github.com/Qithub-BOT/QiiTask/"
  version "0.0.6"

  on_macos do
    url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.6/QiiTask_0.0.6_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "5fd6e856e268e7bcbe8b03675e6b3578a176e09abfaebfa76b065e7a3c56ff99"

    def install
      bin.install "qiitask"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.6/QiiTask_0.0.6_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "7bb6d5544d5e3f58b578db7900d36bd15e1d60f46bcd7f043dc474a7881d8ced"

      def install
        bin.install "qiitask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.6/QiiTask_0.0.6_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e92f075da3a8b09dd5360c0522bd6dcbc6ee5f3c99c103afe56f46936e8c6ded"

      def install
        bin.install "qiitask"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.6/QiiTask_0.0.6_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1a143a42ebe5a8f7b36924d4705d56d3501d89f4b21ec4965404344800993b66"

      def install
        bin.install "qiitask"
      end
    end
  end

  test do
    system "#{bin}/qiitask --version"
  end
end
