# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitask < Formula
  desc "Yet another task management tool."
  homepage "https://github.com/Qithub-BOT/QiiTask/"
  version "0.0.4"

  on_macos do
    url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.4/QiiTask_0.0.4_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "4edb87d2bb934e42687f265cc145774b5798d040f9cb1e0bb360998b5727312e"

    def install
      bin.install "qiitask"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.4/QiiTask_0.0.4_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "9962e82f2d5bf1101b9261d345644d8b144dcaf3df25f46b1d73112bfcb6f546"

      def install
        bin.install "qiitask"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.4/QiiTask_0.0.4_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "42748f645ab89c481bac0b963b4348a8482b6c84969997897a9af8647c499d80"

      def install
        bin.install "qiitask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.4/QiiTask_0.0.4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b87911b0bbe0847cdeed49a8b71e9c16ce82c45b5faa3c95a7b3e14ebf41b659"

      def install
        bin.install "qiitask"
      end
    end
  end

  test do
    system "#{bin}/qiitask --version"
  end
end
