# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitask < Formula
  desc "Yet another task management tool."
  homepage "https://github.com/Qithub-BOT/QiiTask/"
  version "0.0.5"

  on_macos do
    url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.5/QiiTask_0.0.5_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "057f898e96cf69b39a5b99862cd5fc7fe005915c0dc0d20c2408c61ee687b214"

    def install
      bin.install "qiitask"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.5/QiiTask_0.0.5_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "706acceef2ae8f3c58ab493dbba4af93e53d5cad04813ed8ef844fefb06fe759"

      def install
        bin.install "qiitask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.5/QiiTask_0.0.5_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6bc82cca76cd1471ff454acd5fee6d62100ece5a10e749a33d982c5e4aa462c9"

      def install
        bin.install "qiitask"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/QiiTask/releases/download/v0.0.5/QiiTask_0.0.5_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d84c79cc4c1706dd4edac22c4aa599a8a66a10442c43ebdcd4947e30c1552d6f"

      def install
        bin.install "qiitask"
      end
    end
  end

  test do
    system "#{bin}/qiitask --version"
  end
end
