# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiitan < Formula
  desc "This is a sample app of github.com/Qithub-BOT/Qiitan-go. It simply prints 'Hello, Gopher!'."
  homepage "https://github.com/Qithub-BOT/Qiitan-go/"
  version "0.0.0-beta"

  on_macos do
    url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta/Qiitan-go_0.0.0-beta_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "6bdffdbc26887e4a0cb9a963056d2531ea8432fb35bf5d0ca2256fbad08d88cd"

    def install
      bin.install "qiitan"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta/Qiitan-go_0.0.0-beta_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "529f6c61b5765d008ec4b9ca171f9593b5a3bc0ed59eaeee8ccdeb9f6498a335"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta/Qiitan-go_0.0.0-beta_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b92b49d68e1b06e1b1bbb1759505a9acc3e86278100c87fa60b52bb8fc2510a8"

      def install
        bin.install "qiitan"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Qithub-BOT/Qiitan-go/releases/download/v0.0.0-beta/Qiitan-go_0.0.0-beta_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "d6f43b3098989a59fc96c748bee86cd32ee0764d7a30fd3d37d061e1d4c99301"

      def install
        bin.install "qiitan"
      end
    end
  end

  test do
    system "#{bin}/qiitan --version"
  end
end
